version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=sxdb
    volumes:
      - mongodb-local:/data/db
volumes:
 mongodb-local:
  driver: local
